name: data-req-initializer

on:
  workflow_dispatch:
    inputs:
      issue-id:
        description: "Github Issue Number"
        required: true
      dir-name:
        description: "New directory name (ie, lastname-fancy-project)"
        required: true

jobs:
  data_req_init_job:
    runs-on: ubuntu-latest
    name: A job to init a data request
    steps:
      - name: combine inputs to branch name
        id: get-branch-name
        uses: gammaflauge/datareq-init-actions@v0.1
        with:
          issue-id: ${{ github.event.inputs.issue-id }}
          dir-name: ${{ github.event.inputs.dir-name }}
      - name: get the output branch name
        run: echo "the new branch is ${{ steps.get-branch-name.outputs.branch-name }}"
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.get-branch-name.outputs.branch-name }}
