name: data-req-initializer

on:
  workflow_dispatch:
    inputs:
      issue-id:
        description: "Github Issue Number"
        required: true
      dir-name:
        description: "New directory name (ie, lastname-fancy-project)"
        required: true

jobs:
  data_req_init_job:
    runs-on: ubuntu-latest
    name: A job to init a data request
    steps:
      - name: combine inputs to branch name
        id: get-branch-name
        uses: gammaflauge/datareq-init-actions@v0.1
        with:
          issue-id: ${{ github.event.inputs.issue-id }}
          dir-name: ${{ github.event.inputs.dir-name }}

      - name: get the output branch name
        run: echo "the new branch is ${{ steps.get-branch-name.outputs.branch-name }}"

      - name: checkout repo
        uses: actions/checkout@v3

      - name: make a file
        run: echo "# ${{ steps.get-branch-name.outputs.branch-name }}" > myfile.md

      - name: commit readme
        uses: EndBug/add-and-commit@v9
        with:
          message: heres the readme commit msg
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          new_branch: ${{ steps.get-branch-name.outputs.branch-name }}
          add: "myfile.md"
